apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=http://kim-platform.ngrok.io
  - cors=http://kim-platform.ngrok.io
  - env=production
  - skipPermissionsValidation=true
  name: cap-app-proxy-cm
kind: Kustomization
namespace: test-skip-validation
resources:
- ../../base
